### ISSUE TITLE
Cannot define property:__ee__, object is not extensible.

### ISSUE THREAD

**Issue by filipedeschamps** [medikoo/event-emitter#5] opened 2015-01-14 23:33 UTC
Looks like when you use a factory that exports the API with `Object.freeze()`, you receive an error. If I change to `Object.create()` it works.

```
// FACTORY
var createEventEmitter = require('event-emitter');

function createFactory() {
  var emitter = createEventEmitter();

  return Object.freeze({
    emit: emitter.emit,
    on: emitter.on
  });

}

module.exports = createFactory;
```

```
// CONTROLLER
  var instance = createFactory();
  instance.on('test', function(){
    console.log('test');
  });
```

```
// ERROR
TypeError: Cannot define property:__ee__, object is not extensible.
    at defineProperty (native)
    at Object.on (http://localhost:8181/themes/default/scripts/insider-site.js:30534:3)
    at new NewsFeedController (http://localhost:8181/themes/default/scripts/insider-site.js:54:12)
    at invoke (http://localhost:8181/themes/default/scripts/insider-site.js:8624:17)
    at Object.instantiate (http://localhost:8181/themes/default/scripts/insider-site.js:8632:27)
    at http://localhost:8181/themes/default/scripts/insider-site.js:12891:28
    at compile (http://localhost:8181/themes/default/scripts/insider-site.js:4106:28)
    at invokeLinkFn (http://localhost:8181/themes/default/scripts/insider-site.js:12655:9)
    at nodeLinkFn (http://localhost:8181/themes/default/scripts/insider-site.js:12164:11)
    at compositeLinkFn (http://localhost:8181/themes/default/scripts/insider-site.js:11517:13)
```

**Comment by medikoo** [comment] 2015-01-15 08:47
I think when concerning ECMAScript 5 there's no clean solution for that.

This would be fixed only with native WeakMap, so you will need both event-emitter working on WeakMaps, and native WeakMap in engine you work with. I'm closing it as duplicate of #3 as it's exactly same request, lets' continue discussion over there.

**Closed by medikoo** 2015-01-15 08:47 UTC
